import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useMemo } from "react";
import LanguageToggle from "../../components/LanguageToggle";
import ResumeWebsite from "../../components/ResumeWebsite";
import { getResumeInLanguage } from "../../utils/resumeLanguage";
import { decodeResumeData, loadResumeSnapshot } from "../../utils/shareResume";

const emptyData = {
  name: "",
  tagline: "",
  about: "",
  experiences: "",
  skills: "",
  awards: "",
  projects: "",
  projectItems: [],
  email: "",
  github: "",
  linkedin: "",
  mediaItems: [],
  customSections: [],
};

export default function ResumeSharePage() {
  const router = useRouter();
  const slug = typeof router.query.slug === "string" ? router.query.slug : "";
  const encoded = typeof router.query.data === "string" ? router.query.data : "";
  const lang = router.query.lang === "en" ? "en" : "zh";
  const ready = router.isReady;

  const { data, error } = useMemo(() => {
    if (!ready) return { data: emptyData, error: "" };
    if (encoded) {
      try {
        return { data: decodeResumeData(encoded), error: "" };
      } catch {
        return { data: emptyData, error: "分享链接数据无效或已损坏。" };
      }
    }

    const snapshot = loadResumeSnapshot(slug);
    if (snapshot) return { data: snapshot, error: "" };
    return { data: emptyData, error: "未找到该简历内容，请返回编辑器重新发布。" };
  }, [encoded, ready, slug]);
  const displayData = getResumeInLanguage(data, lang);

  return (
    <>
      <Head>
        <title>{data.name ? `${data.name} - Resume` : "Resume"}</title>
        <meta name="description" content="Shared resume generated by MotionCV" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="mx-auto w-full max-w-7xl px-6 py-8 md:px-12 md:py-12">
        <div className="mb-6 flex items-center justify-between rounded-2xl border bg-[var(--panel)] px-5 py-4">
          <div>
            <p className="eyebrow">MOTIONCV SHARE</p>
            <p className="mt-2 text-sm text-[var(--muted)]">可公开访问的个人简历页面</p>
          </div>
          <div className="flex items-center gap-3">
            <LanguageToggle
              lang={lang}
              onChange={(nextLang) => {
                const path = typeof router.asPath === "string" ? router.asPath.split("?")[0] : router.pathname;
                const query = new URLSearchParams();
                if (encoded) query.set("data", encoded);
                query.set("lang", nextLang);
                router.push(`${path}?${query.toString()}`);
              }}
            />
            <Link href="/" className="rounded-full border px-4 py-2 text-xs text-[var(--muted)]">
              返回编辑器
            </Link>
          </div>
        </div>

        {!ready ? (
          <section className="rounded-2xl border bg-[var(--panel)] p-8">
            <p className="text-lg">正在加载简历...</p>
          </section>
        ) : error ? (
          <section className="rounded-2xl border bg-[var(--panel)] p-8">
            <p className="text-lg">{error}</p>
            <p className="mt-3 text-sm text-[var(--muted)]">请返回编辑器重新生成链接。</p>
          </section>
        ) : (
          <ResumeWebsite data={displayData} lang={lang} />
        )}
      </main>
    </>
  );
}
